<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" href="<?php echo $this->baseUrl() . '/css/login.css'; ?>" />
<!--[if IE 6]>
<link href="<?php echo $this->baseUrl() . '/css/ie6.css'; ?>" rel="stylesheet" type="text/css" />
<![endif]-->
<!--[if IE 7]>
<link href="<?php echo $this->baseUrl() . '/css/ie7.css'; ?>" rel="stylesheet" type="text/css" />
<![endif]-->
</head>
<body>
<div class="login">
	<div class="login_wrap">
		<div class="header">
			<div class="header_center">
				<div class="digifolha"><img src="<?php echo $this->baseUrl(); ?>/images/logodigifolha.png" alt="Digifolha"/></div>
				<div class="sistema"><img src="<?php echo $this->baseUrl(); ?>/images/sistema.jpg" alt="Sistema Ipreville"/></div>
			</div>
		</div>
		<div class="login_center">
			<div class="bg_login">
				<div class="centralize">
				<br/>
					<?php echo $this->form;?>
					<?php if (count($this->messages)): ?>
					<p class="erro"><?php echo $this->messages[0]; ?></p>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class="clearfloat"></div>
		<div class="bottom">
			<div class="logos">
				<div class="logos_center">
					<div class="ipreville"><a href="http://www.ipreville.sc.gov.br/" target="_blank"><img src="<?php echo $this->baseUrl(); ?>/images/logo_ipreville.jpg" alt="Ipreville" border="0"/></a></div>
					<div class="jlle"><a href="http://www.joinville.sc.gov.br/" target="_blank"><img src="<?php echo $this->baseUrl(); ?>/images/pref_jlle.jpg" border="0" alt="Prefeitura de Joinville" /></a></div>
				</div>
			</div>
			<div class="rodape">
				<p>Ipreville - Instituto de Previdência Social dos Servidores Públicos do Município de Joinville - Órgão integrante da Prefeitura Municipal - Praça Nereu Ramos, 372, Centro - Joinville/SC - CEP: 89.201-170 - Fone: (47) 3423-1900 - <a href="mailto:ipreville@ipreville.sc.gov.br">ipreville@ipreville.sc.gov.br</a> - <a href="http://www.ipreville.sc.gov.br">www.ipreville.sc.gov.br</a></p>
			</div>
		</div>
		<div class="clearfloat"></div>
	</div>
</div>
<div class="clearfloat"></div>
</body>
</html>