<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title><?php echo $this->layout()->title; ?></title>
<?php echo $this->headMeta() ?>
<link rel="stylesheet" href="<?php echo $this->baseUrl() . '/css/default.css'; ?>" />
<!--[if IE 6]>
<link href="<?php echo $this->baseUrl() . '/css/ie6.css'; ?>" rel="stylesheet" type="text/css" />
<![endif]-->
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
</head>
<body>
<div id="tudo">
	<div id="wrap_p">
		<div class="header">
			<div class="header_left">
				<div class="ipreville"><a href="http://www.ipreville.sc.gov.br/" target="_blank"><img src="<?php echo $this->baseUrl(); ?>/images/logo_ipreville.jpg" alt="Ipreville" border="0" /></a></div>
				<div class="jlle"><a href="http://www.joinville.sc.gov.br/" target="_blank"><img src="<?php echo $this->baseUrl(); ?>/images/pref_jlle.jpg" alt="Prefeitura de Joinville" /></a></div>
			</div>
			<div class="header_center">
				<div class="center">
					<div class="digifolha"><img src="<?php echo $this->baseUrl(); ?>/images/logodigifolha.png" alt="Digifolha" /></div>
					<div class="sistema"><img src="<?php echo $this->baseUrl(); ?>/images/sistema.jpg" alt="Sistema Ipreville" /></div>
				</div>
			</div>
			<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'contatoLogado'), null, true); ?>" class="login_links">
			<div class="header_right">
				Suporte ao Servidor<br />
			</div>
			</a>
		</div>
		<div class="clearfloat"></div>
		<div class="welcome">
			<div class="welcome_bg_r">
				<div id="tbar">
					<div id="tbar_left">
						<p>Olá <span class="b"><?php echo Zend_Registry::get('auth')->getIdentity()->nome; ?></span>. <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'logout'), null, true); ?>">Sair</a></p>
					</div>
				</div>
				<div id="menuPagina">
					<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'contatoLogado', 'id' => 'sa' ), null, true); ?>">
						Solicitar Simulação de Aposentadoria
					</a>
				</div>
			</div>
		</div>
		<div class="main_content2">
			<div id="main2">
				<div class="cont-1">
					<div class="cont-2">
						<div class="cont-3">
							<div class="content">
								<div class="login_2">
									<?php if (count($this->layout()->messages)): ?>
									<div id="messages">
										<?php foreach ($this->layout()->messages as $k): ?>
										<p><?php echo $k; ?></p>
										<?php endforeach; ?>
									</div>
									<?php endif; ?>
									<?php echo $this->layout()->content; ?>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfloat"></div>
			</div>
		</div>
		<div class="clearfloat"></div>
	</div>
	<div id="footer_p">
		<div id="footer_left"></div>
		<div class="footer_center">
			Ipreville - Instituto de Previdência Social dos Servidores Públicos do Município de Joinville - Órgão integrante da Prefeitura Municipal - Praça Nereu Ramos, 372, Centro - Joinville/SC - CEP: 89.201-170 - Fone: (47) 3423-1900 - ipreville@ipreville.sc.gov.br - <a href="http://www.ipreville.sc.gov.br/" target="_blank">www.ipreville.sc.gov.br</a>
		</div>
		<div class="copyright">
			<p>
				Desenvolvido por <a href="http://www.dmgdigital.com.br" target="_blank" class="linkCopyright">DMG Digital</a>
			</p>
		</div>
		<div id="footer_right"></div>
	</div>
	<div class="clearfloat"></div>
</div>
</body>
</html>